config/routes.rb
Rails.application.routes.draw do
  
  root "pages#index"
  
  get 'auth/github/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'repos', to: 'users#repos'
  post 'new_repo', to: 'users#new_repo'
  
  resources :pages, only: [:index]
  resources :users
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/github_repo.rb
class GithubRepo
  attr_reader :name, :full_name, :description
  
  def initialize(attributes = {})
    @name = attributes[:name]
    @full_name = attributes[:full_name]
    @description = attributes[:description]
  end
  def self.for_user(token)
    GithubService.new(token).repos.map do |raw_repo|
      GithubRepo.new(raw_repo)
    end
  end
end

app/models/page.rb
class Page < ApplicationRecord
  
end

app/models/user.rb
class User < ApplicationRecord
  
  def return_avatar
    user = GithubService.new(token).user
    avatar = user[:avatar_url]
  end
  
  def return_star_count
    stars = GithubService.new(token).starred
    stars = stars.count
  end
  
  def return_followers_count
    user = GithubService.new(token).user
    followers = user[:followers]
  end
  
  def return_following_count
    user = GithubService.new(token).user
    following = user[:following]
  end
  
  def return_organization_names
    user_organizations = GithubService.new(token).organizations
    user_organizations.map do |organization|
      organization
    end
  end
  
  def return_repos
    repos = GithubService.new(token).repos
    repos.map do |repo|
      repo
    end
  end
  
  def return_pull_requests(username)
    pull_requests = GithubService.new(token).find_pull_requests(username)
    pull_requests.reject { |pr| pr[0].nil? }
  end 
  
  def return_commits(username)
    commits = GithubService.new(token).find_commits(username)
    commits.map do |commit|
      commit
    end
  end
  
  def return_following_activity
    friend_events = GithubService.new(token).find_friend_events
    friend_events.map do |event|
      event
    end
  end
  
  def return_mentions
    mentions = GithubService.new(token).find_mentions
    mentions.map do |mention|
      mention
    end
  end
  
  def create_repo(name)
    NewRepoService.new(token).create_repo(name = name )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :current_user
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
    if !current_user.nil?
      user = User.find_by(uid: current_user.uid)
      @following_activity = user.return_following_activity
      @mentions = user.return_mentions
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
	def create
    @response = Faraday.post("https://github.com/login/oauth/access_token?client_id=#{ENV['GITHUB_CLIENT_ID']}&client_secret=#{ENV['GITHUB_CLIENT_SECRET']}&code=#{params["code"]}")

	  token = @response.body.split(/\W+/)[1]

	  oauth_response = Faraday.get("https://api.github.com/user?access_token=#{token}")

	  auth = JSON.parse(oauth_response.body)

	  user                = User.find_or_create_by(uid: auth["uid"])
	  user.username       = auth["login"]
	  user.uid			      = auth["id"]
	  user.token	        = token
	  user.save

	  session[:user_id] = user.id

	  redirect_to root_path
	end
  
  def destroy
    session.clear
    redirect_to root_path, flash: { success: "Signed out successfully." }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @presenter = UsersIndexPresenter.new(current_user)
  end
  
  def repos
    user = User.find_by(uid: current_user.uid)
    @repos = user.return_repos
    @pull_requests = user.return_pull_requests(user[:username])
  end
  
  def new_repo
    user = User.find_by(uid: current_user.uid)
    user.create_repo(params["name"])
    redirect_to repos_path
  end
      
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GitShrub</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'spectre', media: 'all' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if current_user %>
    <%= render "logout"  %>
    <% else %>
    <%= render "login" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/_login.html.erb
<ul class="tab tab-block">
  <li class="tab-item">
      <a href="/">GitShrub</a>
  </li>
  <li class="tab-item">
      <%= link_to "Login", "https://github.com/login/oauth/authorize?client_id=#{ENV['GITHUB_CLIENT_ID']}&scope=repo" %>
  </li>
</ul>

app/views/pages/_logout.html.erb
<ul class="tab tab-block">
  <li class="tab-item">
      <a href="/">GitShrub</a>
  </li>
  <li class="tab-item">
    <%= link_to "Repos", repos_path %>
  </li>
  <li class="tab-item">
    <%= link_to "Hello, #{current_user.username}.", users_path %>
  </li>
  <li class="tab-item">
    <%= link_to "Logout", logout_path %>
  </li>
</ul>

app/views/pages/index.html.erb
<body class="landing">
  <h1 class="landing-header">Welcome to GitShrub!</h1>
  
<div class="container center-content">
  <% if current_user %>
    <h3 class="card col-3">Latest from your friends:</h3>
    <% @following_activity.each do |activity| %>
      <% activity.first(3).each do |individual| %>
        <div class="card col-3">
          <div class="card-body">
                <%= link_to individual[:actor][:login], individual[:actor][:url].gsub(/api./, "").gsub(/users/, ""), target: "_blank" %>
                <p>
                  <%= individual[:type].gsub(/Event/, "") %>'d <%= link_to individual[:repo][:name], individual[:repo][:url].gsub(/api./, "").gsub(/\/repos/, ""), target: "_blank" %>
                </p>
          </div>
        </div>
      <% end %>
    <% end %>
    <% end %>
</div>  

<div class="container center-content mentions-align">
  <% if @mentions != [] && if current_user %>
  <h3 class="card card-header col-3">Mentions on:</h3>
  <div class="card col-3">
    <div class="card-body">
      <% @mentions.first(3).each do |mention| %>
        <%= link_to mention[:subject][:title], mention[:subject][:latest_comment_url]
                                                                .gsub(/api./, "")
                                                                .gsub(/\/repos/, "")
                                                                .gsub(/issues/, "pull")
                                                                .gsub(/comments\//, "#{mention[:subject][:url].last(2)}#issuecomment-"), target: "_blank" %>
      <% end %>
    </div>
  </div>
  <% end %>
  <% end %>
</div>
</body>

app/views/users/_logout.html.erb
<ul class="tab tab-block">
  <li class="tab-item">
    <%= link_to "GitShrub", root_path %>
  </li>
  <li class="tab-item">
    <%= link_to "Repos", repos_path %>
  </li>
  <li class="tab-item">
    <%= link_to "Hello, #{current_user.username}.", users_path %>
  </li>
  <li class="tab-item">
    <%= link_to "Logout", logout_path %>
  </li>
</ul>

app/views/users/index.html.erb
<div class="center-content">
  
  <div class="card col-3">
    
    <%= image_tag("#{@presenter.avatar}", class: "card-image img-responsive") %>

    <h3 class="card-header">Hello <%= current_user.username %>!</h3>

    <div class="card-body">
      
      <p>🌟'd repos: <%= @presenter.stars %></p>

      <p>Followers: <%= @presenter.followers %></p>

      <p>Following: <%= @presenter.following %></p>
      
      Member of: <% @presenter.organizations.each do |organization| %>
                      <%= link_to organization[:login], "https://github.com/#{organization[:login]}", target: "_blank" %>
                    <% end %>
    </div>
  </div>

  <div class="card col-3">
    <h3 class="card-header">Repos</h3>
    <div class="card-body">
      <% @presenter.repos.each do |repo| %>
        <%= link_to repo[:name], repo[:html_url], target: "_blank" %>
      <% end %>
    </div>
  </div>

  <div class="card col-3">
    <h3 class="card-header">Commits</h3>
    <div class="card-body">
      <% @presenter.commits.each do |commit| %>
        <% commit.each do |individual| %>
          <% if individual[:type] == "PushEvent" %>
            <%= link_to individual[:payload][:commits][0][:message], individual[:repo][:url].gsub(/api./, "").gsub(/\/repos/, ""), target: "_blank" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

</div>

app/views/users/repos.html.erb
<div class="input-group center-content">
  <%= form_tag(:controller => 'users', :action => 'new_repo') do %>
    New repo name: <%= text_field_tag :name, nil, class: "form-input center-content" %>
    <%= submit_tag "Create new repo!", class: "btn center-content form-button-align" %>
  <% end %>
</div>

<h3 class="card-header center-content pr-alignment-style">Three recent repos:</h3>
<div class="center-content">
  <% @repos.first(3).each do |repo| %>
  <div class="card col-3">
    <h3 class="card-header"><%= link_to repo[:name].titleize, repo[:html_url], target: "_blank" %></h3>
      <div class="card-body">
          <p><%= repo[:description] %></p>
          <p>Forks: <%= repo[:forks_count] %></p>
          <p>Stars: <%= repo[:stargazers_count] %></p>
          <p>Watchers: <%= repo[:watchers_count] %></p>    
      </div>
  </div>
  <% end %>
</div>

<h3 class="card-header center-content pr-alignment-style">Recent pull requests:</h3>
<div class="center-content pr-alignment-style">
  <% @pull_requests[0].each do |pull_request| %>
  <div class="card col-3">
    <h3 class="card-header"><%= link_to pull_request[:title].titleize, pull_request[:html_url], target: "_blank" %></h3>
  </div>
  <% end %>  
</div>